[package]
name = "calc"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.1"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[[bench]]
name = "simulation_bench"
harness = false
